version: '2'
services:
  web:
    build: web/.
    volumes:
      - webdata:/var/www/html
    ports:
      - "8080:80"
    

  db:
    build: db/.
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret

volumes:
  webdata:
  dbdata:
